trigger: none

variables:
- group: version

steps:
  - task: NodeTool@0
    displayName: "Install NodeJS 16.x"
    inputs:
      versionSpec: "16.x"
  - task: npmAuthenticate@0
    inputs:
      workingFile: "$(Build.Repository.LocalPath)/src/.npmrc"
  - script: |
      npm version $(major).$(minor).$(Build.BuildId)
      npm install
      npm run package
    displayName: "Install dependencies and Package app"
  - task: Npm@1
    displayName: 'Publish on NPM'
    inputs:
      command: publish
      publishRegistry: useExternalRegistry
      workingDir: dist
      publishEndpoint: 'NPMJS'